### ISSUE TITLE
suggestion: way to sort staff by other an ASC/DESC alphabetical

### ISSUE THREAD

**Issue by ndebard** [brettshumaker/Staff-List-Plugin#71]
Seniority?  Drag/drop/reorder?

I dislike not being able to sort them to my liking :).

**Comment by brettshumaker** [comment]
Currently, there is a drag/drop reorder on the plugin's "Order" screen.

I'll be adding in some filters soon - including one that makes the staff loop WP_Query args available.

**Comment by craigjwaldron** [comment]
Any update on the order function?

**Comment by brettshumaker** [comment]
@craigjwaldron Not yet, unfortunately. :( I think this issue fell through the cracks as I've not yet implemented that filter.

But sorting by last name is an entirely different beast since there has to be a massive data conversion that happens and splits existing staff member names into multiple fields. Difficult to do that reliably. See #57
